### ISSUE TITLE
Crashes/Exits Gulp on Syntax Error

### ISSUE THREAD

**Issue by eudaimos** [ortexx/gulp-forever-monitor#2]
My use case is to use forever to monitor my code in a continuous loop during development and automatically restart server upon code changes.

Unfortunately because in `child.on('stderr')` handler, `process.exit(1)` is being called, anytime a syntax error is introduced in the code, I have to restart my gulp task.

I've created PR #1 to remove this issue.

**Comment by ortexx** [comment]
Fixed, thanks! =)

**Comment by eudaimos** [comment]
@ortexx can you please publish an update to NPM with this change?

Also, it would probably make sense to tag the repo with the version you push to NPM

**Comment by ortexx** [comment]
Already published. Current version 0.0.2

**Comment by eudaimos** [comment]
Thanks, it was my bad.

Not sure why (w/o looking it up) but the package installs with hard set version `0.0.1` so when I reinstalled from `npm install` it didn't get the update.  I've updated it and I also see another improvement that I'll create a new PR for to remove the double printing of error messages (can cause confusion as to what's running)

**Comment by eudaimos** [comment]
@ortexx 

Would you mind using the [Releases](../releases) or [Tags](../tags) features of Github/git to version the code with the NPM package?
This makes it a lot easier to use the package.

Thanks again for writing this plugin.

**Comment by ortexx** [comment]
I will create, if there are some other changes. 
Thanks!
