### ISSUE TITLE
How to restart forever process

### ISSUE THREAD

**Issue by lukasoppermann** [ortexx/gulp-forever-monitor#4]
Hey, can you please let me know how I can restart a forever process from within a gulp task? Thanks.

**Comment by ortexx** [comment]
Hi! As i remember, you can save forever process to a variable and call __.restart__ method anytime you want.

```
let child = forever('server.js', foreverMonitorOptions) ;

child.restart();
```

You can see all monitor methods here https://github.com/foreverjs/forever-monitor/blob/master/lib/forever-monitor/monitor.js

**Comment by lukasoppermann** [comment]
Okay, this did not work for me. I thought that was due to this package, but may I just had an error. If it is supposed to work this way I will try some more. Thank you for the quick reply.
